### ISSUE TITLE
--release doesn't do what I expect

### ISSUE THREAD

**Issue by techtangents** [oscarotero/keep-a-changelog#18]
I'd like to run a command which releases the Unreleased section.

e.g. before:

```
## [Unreleased]
### Added
- feature1
- feature2
```

after:

```
## [Unreleased]

## [1.2.3] - 2021-03-01
### Added
- feature1
- feature2
```

`yarn changelog --release` doesn't seem to do this. My changelog gets normalized, but nothing else seems to happen.

**Comment by oscarotero** [comment]
It's because you don't have the number of the unreleased version. ATM, this library doesn't generate the new version number because it can be a patch, minor or major version. This command was created to generate automatically the release date in this case:

```md
## [1.2.3] - Unreleased
### Added
- feature1
- feature2
```

Maybe, a way to generate the version number is implementing something like `--release=minor`, `--release=major`, etc.

**Comment by techtangents** [comment]
For my use case, it'd be convenient to pass in the version number. e.g.

```
--release 1.2.3
```

or

```
--release --version 1.2.3
```

**Comment by oscarotero** [comment]
Ok, that's easier. I'll do that.

**Comment by oscarotero** [comment]
Done!
v0.10.4 released. Now you can run `--release 1.2.3`

**Comment by techtangents** [comment]
Wow, that was fast. Thank you very much!

Are you able to please add a new `# Unreleased` header above that?
